spring:
  shardingsphere:
    props:
      sql:
        show:
          true
    datasource:
      names: db_0,db_1
      db_0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db0
        username: root
        password:
      db_1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db1
        username: root
        password:
    sharding:
      tables:
        # 逻辑表名
        t_order_master:
          actualDataNodes: db_0.orders_$->{[0,2,4,6,8,10,12,14,16,18,20,24,26,28,30,32]},db_1.orders_$->{[1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31]}
          keyGenerator:
            column: id
            type: SNOWFLAKE
          databaseStrategy:
            inline:
              algorithmExpression: db_$->{id % 2}
              shardingColumn: id
          tableStrategy:
            inline:
              algorithmExpression: orders_$->{id % 16}
              shardingColumn: id
logging:
  level:
    root: info
    org.springframework.jdbc.core: info